name: Validate Redirects

on:
  pull_request:
    paths:
      - '_redirects'
      - 'validate_redirects.py'
  push:
    branches: [main]
    paths:
      - '_redirects'
      - 'validate_redirects.py'

jobs:
  validate-redirects:
    runs-on: ubuntu-latest
    name: Redirect Validator

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run validator
        run: python validate_redirects.py _redirects
